language: python
python:
  - "3.5"
cache: pip
install: 
  - "pip install cython"
  - "pip install numpy" 
  - "pip install prospercommon --no-cache-dir"
  - "travis_wait 15 pip install ."
script: 
  - "python scripts/manage_api.py --testkey"
  - "python scripts/create_splitcache.py --regions=10000002 --type=34 --range=30 --db=publicAPI/cache/travis_splitcache.json --source=esi"
  - "python setup.py test"
branches:
  only:
  - master
  - travis_test
after_success:
  - "pip install python-coveralls"
  - "coveralls"
